<section  class="container container-website col-lg-10 col-lg-offset-1 ">
	<div class="black-box col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
		<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">صور  |  إذاعة  وتلفزة</h3>
		</div>
		<?php } else { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">PHOTOS  |  TV & RADIOS</h3>
		</div>
		<?php } ?>
	</div>

	<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1" style="padding: 0px; margin-bottom: 60px;">
    	<!-- Radios -->
    	
    	<?php foreach ($this->gallery as $key => $ms) {  ?>
    		<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="<?= $ms['img'] ?>" src="<?= $ms['thumb'] ?>" rel="group1"/></span>
    	<?php } ?>
    	<!-- <span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_01.jpg" src="images/radio/fatine_miniature_01.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_02.jpg" src="images/radio/fatine_miniature_02.jpg" rel="group1"/></span>
    	<span class="col-lg-4  col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_03.jpg" src="images/radio/fatine_miniature_03.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_04.jpg" src="images/radio/fatine_miniature_04.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_05.jpg" src="images/radio/fatine_miniature_05.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_06.jpg" src="images/radio/fatine_miniature_06.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_07.jpg" src="images/radio/fatine_miniature_07.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_08.jpg" src="images/radio/fatine_miniature_08.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_09.jpg" src="images/radio/fatine_miniature_09.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_10.jpg" src="images/radio/fatine_miniature_10.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_11.jpg" src="images/radio/fatine_miniature_11.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_12.jpg" src="images/radio/fatine_miniature_12.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_13.jpg" src="images/radio/fatine_miniature_13.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_14.jpg" src="images/radio/fatine_miniature_14.jpg" rel="group1"/></span>
        <span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_15.jpg" src="images/radio/fatine_miniature_15.jpg" rel="group1"/></span>
        <span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" data-glisse-big="images/radio/fatine_16.jpg" src="images/radio/fatine_miniature_16.jpg" rel="group1"/></span> -->  
	</div>
	<!-- <div class="ref-item col-lg-4 col-md-6 <?= $ref['cat'] ?>">
						        <a href="references/detail/id/<?= $ref['pid'] ?>"><div class="article"><img width="100%" height="266px" src="<?= $ref['img'] ?>" /></div>
							    <h5><?= $ref['title'] ?></h5></a>
						      	<h6 style="text-align: justify;"><?= $ref['cat'] ?></h6>
			        		</div> -->
	<script>
		$(function () {
		    $('.pics').glisse({
		        changeSpeed: 550, 
		        speed: 500,
		        effect:'fadeBig',
		        fullscreen: false
		    }); 
		});
	</script>
	<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
	<style type="text/css">
	h3, .about p {
	font-family: 'DroidKufi-Bold.ttf';
}
	.ticket-rub {
	    text-align: left;
	    float: left;
	    margin-left: -30px;
	}

	.title-rub {
	    text-align: right;
	    margin-right: -30px;
	    float: right;
	}

	</style>
	<?php } ?>	
</section>