<script type="text/javascript" src="bootstrap/js/isotop.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/slick.css"/>

<link rel="stylesheet" type="text/css" href="css/slick-theme.css"/>

<script type="text/javascript" src="bootstrap/js/slick.min.js"></script>

<link rel="stylesheet" type="text/css" href="owl/assets/owl.carousel.css">

<script type="text/javascript" src="owl/owl.carousel.js"></script>
<script type="text/javascript" src="bootstrap/js/script.js"></script>

<section class="container container-slide col-lg-10 col-lg-offset-1">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img width="100%" class="first-slide" src="images/slide-ben.jpg" alt="First slide">
        </div>
        <div class="item">
          <img width="100%" class="second-slide" src="images/slide-ben.jpg" alt="Second slide">
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left glyphicon-left-modif" aria-hidden="true" ></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right glyphicon-right-modif" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</section>

<section  class="container container-website col-lg-10 col-lg-offset-1 ">
	<div class="black-box col-lg-10 col-lg-offset-1 col-xs-12 col-md-10 col-md-offset-1">
		<div class="rub">
			<h3 class="col-lg-8 col-xs-6  title-rub">MUSIQUE</h3>
			<a href="#"><h3 class="col-lg-4 ticket-rub"><span>+ DE MUSIQUE &nbsp;&nbsp;<img src="images/arrow.png" /></span></h3></a>
		</div>
	</div>
</section>
<section  class="container container-website col-lg-10 col-lg-offset-1" style="padding: 0px; margin-top:0px;">
	<div id="images" class="col-lg-12" >
		<div class="owl-carousel-images">
		    <div class="item-image col-md-12 col-xs-8 col-md-offset-0 col-xs-offset-2"><img src="imgs/img1.jpg"></div>
		    <div class="item-image col-md-12 col-xs-8 col-md-offset-0 col-xs-offset-2"><img src="imgs/img2.jpg"></div>
		    <div class="item-image col-md-12 col-xs-8 col-md-offset-0 col-xs-offset-2"><img src="imgs/img3.jpg"></div>
		    <div class="item-image col-md-12 col-xs-8 col-md-offset-0 col-xs-offset-2"><img src="imgs/img2.jpg"></div>
		    <div class="item-image col-md-12 col-xs-8 col-md-offset-0 col-xs-offset-2"><img src="imgs/img3.jpg"></div>
		</div>
		<div class="navigation img"></div>
	</div>
</section>


<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1 col-xs-12 col-md-10 col-md-offset-1">
		<div class="rub">
			<h3 class="col-lg-8 col-xs-6  title-rub">EN VIDEOS</h3>
			<a href="#"><h3 class="col-lg-4 ticket-rub"><span>+ DE VIDEOS &nbsp;&nbsp;<img src="images/arrow.png" /></span></h3></a>
		</div>
	</div>
</section>

<section  class="container container-website col-lg-10 col-lg-offset-1" style="padding: 0px; margin-top:0px;">
	<div id="slider" class="col-lg-12" style="margin-bottom: 60px;">
		<div class="owl-carousel-video">
		    <div class="item-video" data-merge="3"><a class="owl-video" href="https://www.youtube.com/watch?v=bPsBRsC2s0M"></a></div>
		    <div class="item-video" data-merge="3"><a class="owl-video" href="https://www.youtube.com/watch?v=mB1sZAnP_MA"></a></div>
		    <div class="item-video" data-merge="3"><a class="owl-video" href="https://www.youtube.com/watch?v=nY0BWzD04Rs"></a></div>
		    <div class="item-video" data-merge="3"><a class="owl-video" href="https://www.youtube.com/watch?v=jstyG45zFEw"></a></div>
		</div>
		<div class="navigation vid"></div>
	</div>
</section>
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1 col-xs-12 col-md-10 col-md-offset-1">
		<div class="rub">
			<h3 class="col-lg-8 col-xs-6  title-rub">EN PHOTOS</h3>
			<a href="#"><h3 class="col-lg-4 ticket-rub"><span>+ DE PHOTOS &nbsp;&nbsp;<img src="images/arrow.png" /></span></h3></a>
		</div>
	</div>
	<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1" style="padding: 0px; margin-bottom: 60px;">
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" src="images/album1.jpg" data-glisse-big="images/album1.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" src="images/album2.jpg" data-glisse-big="images/album2.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" src="images/album3.jpg" data-glisse-big="images/album3.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" src="images/album4.jpg" data-glisse-big="images/album4.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" src="images/album5.jpg" data-glisse-big="images/album5.jpg" rel="group1"/></span>
    	<span class="col-lg-4 col-xs-4 col-md-4"><img class="pics" src="images/album6.jpg" data-glisse-big="images/album6.jpg" rel="group1"/></span>
	</div>
	<script>
		$(function () {
		    $('.pics').glisse({
		        changeSpeed: 550, 
		        speed: 500,
		        effect:'fadeBig',
		        fullscreen: false
		    }); 
		});
	</script>
</section>


