
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<div class="rub">
			<h3 class="col-lg-12 title-rub">VIDEOS</h3>
		</div>
	</div>

	<div class="col-lg-10 col-lg-offset-1 videos" style="padding: 0px; margin-bottom: 60px;">
	  	<!-- discographie -->
	  	<span class="col-lg-4 col-md-4 col-xs-4 relative"><span class="col-lg-4 col-md-4 col-xs-4 absolute"></span>
	  	<img width="100%" src="imgs/img1.jpg" /></span>

	  	<style>
	  		span.relative {
			    position: relative;
			    width: 90%;
			    background-color: red;
			    height: 100%;
			    opacity: 0.4;
			} 

			span.absolute {
			    position: absolute;
			}

			span.absolute:hover {
			    width: 90%;
			    background-color: red;
			    height: 100%;
			    opacity: 0.4;
			}
	  	</style>
	</div>
	<!-- <div class="ref-item col-lg-4 col-md-6 <?= $ref['cat'] ?>">
						        <a href="references/detail/id/<?= $ref['pid'] ?>"><div class="article"><img width="100%" height="266px" src="<?= $ref['img'] ?>" /></div>
							    <h5><?= $ref['title'] ?></h5></a>
						      	<h6 style="text-align: justify;"><?= $ref['cat'] ?></h6>
			        		</div> -->
</section>