<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<div class="rub">
			<h3 class="col-lg-12 title-rub">AUTHENTIFICATION</h3>
		</div>
	</div>
	<div class="col-lg-10 col-lg-offset-1 ">
		<div class="col-lg-8 col-lg-offset-2">
			<form id="contact-form" method="post" class="col-lg-12 form-contact" style="margin-top: 40px;"></span>
				<?php if(isset($this->loginfailed)) { ?>
				<div class="col-lg-12 alert alert-danger" role="alert"><?= $this->loginfailed ?></div>
				<?php } ?>
				<span class="col-lg-12"><input type="text" value="" name="user" value="Administrateur" ></span>
				<span class="col-lg-12"><input type="password" value="" name="pass" value="Mot de Passe" ></span>
				<span class="col-lg-12"><input type="hidden" value="1" name="completed" ></span> 
				<span class="col-lg-4 col-lg-offset-4"><input type="submit" value="Se connecter" ></span>
			</form> 
		</div>
	</div>
</section>
