
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<div class="rub">
			<h3 class="col-lg-12 title-rub">VIDEOS</h3>
		</div>
	</div>

	<div class="col-lg-10 col-lg-offset-1 videos" style="padding: 0px; margin-bottom: 60px;">
	  	<!-- Videos -->
		<iframe width="100%" src="<?= $ref['link'] ?>" frameborder="0" allowfullscreen></iframe>
		<iframe width="100%" src="https://www.youtube.com/embed/nY0BWzD04Rs" frameborder="0" allowfullscreen></iframe>
		<iframe width="100%" src="https://www.youtube.com/embed/bPsBRsC2s0M" frameborder="0" allowfullscreen></iframe>
	</div>
</section>