
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">فيدوهات</h3>
		</div>
		<?php } else { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">VIDEOS</h3>
		</div>
		<?php } ?>
	</div>

	<div class="col-lg-10 col-lg-offset-1 videos" style="padding: 0px; margin-bottom: 60px;">
	  	<!-- Videos -->
	  	<?php foreach ($this->videos as $key => $ms) { ?>
	  		<iframe width="100%" src="<?= str_replace('watch?v=', 'embed/', $ms['link']) ?>" frameborder="0" allowfullscreen></iframe>
	  	<?php } ?>
		<!-- <iframe width="100%" src="<?= $ref['link'] ?>" frameborder="0" allowfullscreen></iframe>
		<iframe width="100%" src="https://www.youtube.com/embed/nY0BWzD04Rs" frameborder="0" allowfullscreen></iframe>
		<iframe width="100%" src="https://www.youtube.com/embed/bPsBRsC2s0M" frameborder="0" allowfullscreen></iframe> -->
	</div>
</section>
<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
<style type="text/css">

h3, .about p {
	font-family: 'DroidKufi-Bold.ttf';
}

.ticket-rub {
    text-align: left;
    float: left;
    margin-left: -30px;
}

.title-rub {
    text-align: right;
    margin-right: -30px;
    float: right;
}

</style>
<?php } ?>	

