<html>
<head>
	<title>FATINE BENAGUIDA</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap-theme.min.css">

	<!-- Main Style -->
	

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<!--<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'> -->

	<!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,700,300' rel='stylesheet' type='text/css'> -->

	<!-- Jquery -->
	<script src="bootstrap/js/jquery.min.js"></script>
	<script src="bootstrap/js/function.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="bootstrap/js/bootstrap.min.js"></script>

	<script src="bootstrap/js/jquery.cycle.all.min.js"></script>
	<script src="bootstrap/js/jflickrfeed.min.js"></script>
	<script src="bootstrap/js/setup.js"></script>

	<link rel="shortcut icon" href="images/ico-fatin.png" type="image/x-icon"> 
	<link rel="stylesheet" href="css/style.css">

	<script src="bootstrap/js/glisse.js"></script>
	<link rel="stylesheet" href="css/glisse.css" />
	
	<!-- <script type="text/javascript" src="bootstrap/js/isotop.min.js"></script> -->

</head>
<body>
	<header>
		<section class="col-lg-10 col-lg-offset-1 righttoleft">
			<div class="langue">
				<a href="?lang=FR-fr">Fr</a>
				<a href="?lang=AR-ar">Ar</a>
			</div>
		</section>
		<style>
		.langue { margin-bottom: 4px; margin-right: -20px;}
		.langue a { 
			color: white;
		    background-color: #d14e3d;
		    padding: 2px 4px;
		    text-decoration: none;
		    border-radius: 3px;
		    margin-right: 4px;
		}

		.langue a:hover { 
			color: white;
		    background-color: #000;
		    cursor: pointer;
		}
			    
		</style>
		<nav class="col-lg-10 col-lg-offset-1 navbar navbar-default modif1">
	      <div class="container" id="div-title" style="">
	        <div class="col-lg-12 center-header  
	        	<?= (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) ? 'arab' : 'french' ?>
	        	">
		        <div class="logo-title">
		        	<?php //if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
		        	<!-- <a href="/projects/fatine-blog/public/"><span style="font-family: BebasNeue;">فاتن بنعكيدة</span></a> -->
		        	<?php //} else { ?>
		        	<a href="/projects/fatine-blog/public/"><span style="font-family: BebasNeue;">FATINE BENAGUIDA</span></a>
		        	<?php //} ?>
		        </div>
		        <div class="navbar-header">
		          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button> 
		        </div>
		        <?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
			        <div id="navbar" class="navbar-collapse collapse-in collapse col-lg-6 col-xs-12">
			            <ul id="main-menu" class="nav navbar-nav main-menu-ar" >
							<li class="<?= $this->contact ?>"><a href="contact?lang=AR-ar">تواصل&nbsp;&nbsp;&nbsp;معنا</a></li>
							<li><a href="event?lang=AR-ar">أحداث</a></li>
							<li class="parent <?= $this->galerie ?>">
								<a href="#">صور</a>
								<ul class="sub-menu">
									<li>
										<a class="parent"><i class="icon-file-alt"></i>صور</a>
										<ul class="sub-menu">
											<li><a href="radios?lang=AR-ar"> إذاعة و تلفزة</a></li>
											<li><a href="festivals?lang=AR-ar">مهرجانات</a></li>
											<li><a href="revues?lang=AR-ar">صحافة</a></li>
											<li><a href="divers?lang=AR-ar">آخر</a></li>
										</ul>
									</li>
									<li><a href="videos?lang=AR-ar"><i class="icon-wrench"></i>فيديوهات</a></li>
								</ul>
							</li>
							<li class="<?= $this->discographie ?>"><a href="discographie?lang=AR-ar">موسيقى</a></li>
							<li class="<?= $this->about ?>"><a href="about?lang=AR-ar">تعريف</a></li>
							<li class="<?= $this->home ?>"><a href="/projects/fatine-blog/public/?lang=AR-ar">الرئيسية</a></li>
						</ul>
					</div><!--/.nav-collapse -->
				<?php } else { ?>
				<div id="navbar" class="navbar-collapse collapse-in collapse col-lg-8 col-xs-12">
					<ul id="main-menu" class="nav navbar-nav " >
						<li class="<?= $this->home ?>"><a href="/projects/fatine-blog/public/">Accueil</a></li>
						<li class="<?= $this->about ?>"><a href="about">Biographie</a></li>
						<li class="<?= $this->discographie ?>"><a href="discographie">Discographie</a></li>
						<li class="parent <?= $this->galerie ?>">
							<a href="#">Galerie</a>
							<ul class="sub-menu">
								<li>
									<a class="parent"><i class="icon-file-alt"></i>Photos</a>
									<ul class="sub-menu">
										<li><a href="radios">TV & Radios</a></li>
										<li><a href="festivals">Festivals</a></li>
										<li><a href="revues">Revues de presse</a></li>
										<li><a href="divers">Divers</a></li>
									</ul>
									
								</li>
								<li><a href="videos"><i class="icon-wrench"></i>Vidéos</a></li>
							</ul>
						</li>
						<li><a href="event">ÉVÉNEMENTS</a></li>
						<li class="<?= $this->contact ?>"><a href="contact">Contact</a></li>
					</ul>
				</div><!--/.nav-collapse -->
				<?php } ?>

		        
		       </div>
	      </div>
	    </nav>
	</header>
	<?php echo $this->layout()->content; ?>	
	<footer>
			<div class="copyright">
				<div class="container">
					<div class="row1-footer">
						<div class="col-lg-6 col-lg-offset-3">
							<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
							<p style="color: #000;">جميع الحقوق محفوظة&nbsp;&nbsp;&nbsp;2015&nbsp;&nbsp;&nbsp;فاتن بنعكيدة تصميم&nbsp;&nbsp;&nbsp;MEDIA TUCH</p>
							<?php } else { ?>
							<p style="color: #000;">© 2015 fatine benaguida. TOUS DROITS RÉSERVÉS.&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;conçu par : MEDIA TUCH</p>
							<?php } ?>
						</div>
					</div>			
				</div>
			</div>
	</footer>

	<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
		<style>
			* {
				font-family: 'DroidKufi-Bold.ttf';
			}
			a, p, nav, .righttoleft {
				direction: rtl !important;
			}

			.main-menu-ar {margin-left: 0px !important;}

			#main-menu li a { font-size: 20px;}

			ul.sub-menu { right:0px;}

			ul.sub-menu ul.sub-menu { right: 179px;}

			ul.sub-menu > li > a.parent {
			    background-image: url(images/arrow-ar.png);
			    background-position: 5% center;
			}
		</style>
	<?php } ?>
</body>
</html>

