
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">أحداث</h3>
		</div>
		<?php } else { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">EVENEMENTS</h3>
		</div>
		<?php } ?>
	</div>

	<div class="col-lg-10 col-lg-offset-1 events" style="padding: 0px; margin-bottom: 40px;">
	  	
		<?php foreach ($this->events as $key => $ms) { ?>
		<div class="col-lg-6 col-xs-12" style="padding: 0px; margin-bottom: 20px;">
	  		<div class="col-lg-6 col-md-6 col-xs-10">
	  			<img src="<?= $ms['img'] ?>">
	  		</div>
	  		<div class="col-lg-6 col-xs-10">
	  			<h3><?= $ms['title'] ?></h3>
	  			<h5><?= $ms['date'] ?></h5>
	  			<h5><?= $ms['description'] ?></h5>
	  		</div>
	  	</div>	
		<?php } ?>
	  	<!-- <div class="col-lg-6">
	  		<div class="col-lg-6">
	  			<img src="images/event.jpg">
	  		</div>
	  		<div class="col-lg-6">
	  			<h3>FESTIVAL MAWAZINE</h3>
	  			<h5>16 MAI 2016</h5>
	  			<h5>SCENE RABAT - ANAHDA</h5>
	  		</div>
	  	</div>
	  	<div class="col-lg-6">
	  		<div class="col-lg-6">
	  			<img src="images/event.jpg">
	  		</div>
	  		<div class="col-lg-6">
	  			<h3>FESTIVAL MAWAZINE</h3>
	  			<h5>16 MAI 2016</h5>
	  			<h5>SCENE RABAT - ANAHDA</h5>
	  		</div>
	  	</div> -->
	</div>
	<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
	<style type="text/css">
	.ticket-rub {
	    text-align: left;
	    float: left;
	    margin-left: -30px;
	}

	.title-rub {
	    text-align: right;
	    margin-right: -30px;
	    float: right;
	}

	</style>
	<?php } ?>	
</section>


