<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
		<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">تعريف</h3>
		</div>
		<?php } else { ?>
		<div class="rub">
			<h3 class="col-lg-12 title-rub">BIOGRAPHIE</h3>
		</div>
		<?php } ?>
	</div>
	<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
		<div class="about">
			<img src="images/biographie.jpg" width="100%"/>
			<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
			<h2 style="direction: rtl !important; color: #d14e3d;">"فاتن بنعكيدة" جوهرة مدينة الخميسات و مفخرة منطقة الأطلس و البلد بأكمله.</h2>
			<p style="text-indent: 40px; color: #ffe55e; margin-bottom: -20px;">الطموح، المثابرة و الإصرار على النجاح، ثلاثية  كانت دعامة الفنانة "فاتن" لتحقيق طموحاتها في الحياة.</p>
			<p>فاطمة الزهراء بنعكيدا هو إسمها الحقيقي، فنانة مغربية الأصل والهوية ولدت وترعرعت بمدينة الخميسات  القلب النابض لمنطقة الأطلس. 
			رأت النّور، في 5 مارس ،  اكتشفت أولى قدراتها الصوتية من خلال ترتيلها لآيات  قرآنية منذ نعومة أظافرها... ثم من خلال الأنشطة المدرسية: المسرح، الغناء.....احترافها للفن يظهر شيئا فشيئا، خاصة عند أدائها لأغاني عمالقة الفن: أم كلثوم، فيروز، وردة... 
			سواء أكانت حفلات أو مسابقات فنية.. لا شيئ من هذا القبيل تتركه" فاتن" يمر مرور الكرام دون أن تشارك فيه، يلازمها الإحباط أحيانا و لكن الفرح يكون سيد الموقف، لتتفاجأ بجمهورها الذي يزداد عدده و تزداد ثقته فيها كفنانة تتميز بصوت آسر و متفرّد. 
			برنامج "أضواء المدينة "الذي قدمه "إدريس التاديلي"،كان أول فرصة لها لإسماع صوتها فغنت "للصبر حدود" لكوكب الشرق أم كلثوم . 
			كان البرنامج التلفزي " قافلة التنمية"  فرصة أخرى "لفاتن" لتوسِّع من دائرة معجبيها ، غنت للفنانة لطيفة رأفت أغنيتها"أنا في عارك يا يمّا" فعزفت اوركسترا هلال تطوان أعذب الألحان بقيادة المايسترو بن براهيم. 
			</p>

			<p>حصدت فاتن إعجاب أسماء فنية كبيرة كالفنان "فتح الله لمغاري " و الراحل محمد الحياني الذي شاركته إحدى المهرجانات الفنية بمدينة الخميسات، و أثنى على موهبتها كفنانة صاعدة ستضيف للأغنية العصرية  على غرار الفنانة لطيفة رأفت و نعيمة سميح و سميرة بنسعيد.حالت الظروف المادية دون وصول الفنانة "فاتن" لمبتغاها،فباءت محاولاتها بالفشل، إلى أن اقتنعت بفكرة شركات الإنتاج، فاتجهت صوب الأغنية الشعبية. </p>

			<p>خلدت الفنانة " فاتن" مسيرتها الفنية، بأغنية أسطورية لاقت الإعجاب وظلت راسخة في أذهان المغاربة على مر هذه السنين.أغنية "العظمة ما منّوش" من تأليف و تلحين الفنانة " فاتن"، وقامت بتسجيلها بالدار البيضاء  مع شركة الإنتاج " الفنون الشعبية لمدينة الخميسات"." العظمة ما منّوش " تم إصدارها في سنة 1987، حققت نجاحا منقطع النظير في المغرب و على الصعيد العالمي خاصة المغاربي و في دول الخليج العربي.</p>

			<p>إمتطلبات السوق الفنية حالت دون تمكّن الشركة المنتجة من التوزيع الجيد للأغنية فترك المجال واسعا للقرصنة التي هددت و تهدد كل إنتاجات الفنانين بصفة عامة. فنانون كثر إستهوتهم أغنية " العظمة ما منّوش" فقاموا بأدائها: ميلودة، ريموند، رشيد لمريني، العسري،سيف و اخرون .....</p>

			<p>قامت الفنانة " فاتن" بجولة فنية اخذتها لبلدان عديدة لتتوقف في بلجيكا و تستقر هناك.بالموازات مع الفن، أتممت " فاتن" دراستها لتبحر في الميدان الاجتماعي كإنسانة متواضعة وكريمة ، تحب مساعدة الآخرين ، و الى يومنا هذا ، فهي ترعى الأشخاص المسنين في مستشفى للأمراض العصبية،و هي أيضاً أم  لثلاثة أطفال ( ولدين و بنت).</p>

			<p>رغما عنها، غابت "فاتن" عشرين سنة عن الساحة الفنية، ومحاولات العائلة و المقربين و الفنانين الأصدقاء، تكللت بالنجاح من أجل إقناع "فاتن" للعودة إلى المجال الفني.</p>

			<p>أعادت فاتن أداء أغنية *العظمة مامنوش*  و قامت بتسجيلها بتوزيع يتماشى مع السوق الحالية بتعاون مثمر مع الكاتب توفيق أبو زهير و الملحن والموزع مراد الكزناي، فكانت  العودة قوية . 	</p>

			<p>العظمة ما منّوش عودة منطقية لأغنية تركت بصمتها في المجال الفني، "فاتن بن عكيدة" لن تتوقف عند هذا الحد، مفاجاءات كثيرة تعد بها جمهورها، لتشق طريقها في ميدان الأغنية المغربية العصرية، و تحقق بذلك حلم الطفولة.</p>

			<p>بعد تجديد و إطلاق أغنيتها الأسطورة " العظمة مامنوش"، في شهر مارس 2015 ؛ فاتن بنعكيدة الملقبة بجوهرة الخميسات؛ تفي بوعدها و تطلق جديدها سد الباب.</p>

			<p>الأغنية التي مدتها 3 دقائق و 50 ثانية، من كلمات و ألحان الفنان المقتدر عماد المغربي و من توزيع بدر المخلوقي.</p>

			<p>ففي الواقع ، سد الباب هي أغنية افتتاح  لسلسلة من الأغاني الجديدة ؛ حضرتها الفنانة فاتن لإرضاء جمهورها القديم و محبيها الجدد والسماح لها للتألق في سماء الأغنية المغربية</p>

			<p>المرحلة الموالية و السينجل القادم تخصصهم الفنانة فاتن بنعكيدة لمسقط رأسها و ستكون الأغنية عبارة عن صرخة تكريمية .</p>
			<?php } else { ?>

			<h2 style="color: #d14e3d;">Fatine BENAGUIDA : Le joyau de la ville de Khemisset , la fierté de la région l'Atlas et de tout un Pays .</h2>
			<p>Fatima Zahra BENAGUIDA , native de la ville de Khemisset le coeur palpitant de la région de l'Atlas , ville connue par la générosité et l'intégrité de ses citoyens .</p>

			<p>Elle est née le 05 Mars 1966. Elle a découvert ses premières forces de cordes vocales à travers la lecture coranique à son très jeune âge.</p>

			<p>Puis à travers des activités parascolaires ; comme le théâtre et le chant, sa vocation artistique se confirme petit à petit,   surtout avec de grandes interprétations à des classiques de <b>Oum Kalthoum</b>,  de <b>Fairouz</b>, de <b>Warada</b>  ...</p>

			<p>Les fêtes nationales , les concours .. Rien ne lui échappe ... Des fois déçue par les résultats mais souvent agréablement surprise par l'amour d'un public qui commence peu à peu à réclamer sa voix distinguée.</p>

			<p>Sa première intervention à la radio à l’émission « Adwaa Al Madina » avec <b>Mr. Driss TADILI</b> et où elle a interprété « Li Sabr Hdoud » Vient après, Son premier  passage à la télévision marocaine à l'émission «  kafilat tanmya » , où elle a interprété la chanson « Ana faarak ya yamma » de l'artiste <b>Latifa Raafat</b> . Une interprétation remarquable appuyée par l'orchestration inédite de l'orchestre « al hilal de tetouan » , dirigé à l’époque  par le Maestro BENBRAHIM ;  et amplement appréciée par   de  grands    noms   de   la   chanson   marocaine   comme    <b>Mr. Fathallah LAMGHARI</b>.</p>

			<p>Aussi, le témoignage du défunt <b>Mohamed El Hyani</b> , avec qui , elle a partagé la Scène d'un festival à la ville de Khemisset , lui a confirmé son talent et sa détermination pour l'évolution dans la chanson marocaine moderne suivant la voix de <b>Naima SAMIH , Latefa RAAFAT, Samira SAID ...</b></p>

			<p>Mais pour des raisons financières suite à une séparation parentale, et sans trop le vouloir , Fatima se retrouve dans l'engrenage des producteurs , qui après plusieurs tentatives finissent par la convaincre de mettre sa voix au service de la chanson populaire. Ainsi est née la chanson mythique <b>« Al adama Mamennouch »</b>, écrite et composée par l'artiste même et enregistrée à Casablanca avec la société de production <b>« AL FOUNOUN CHAABYA LI MADINAT AL KHEMISSET »</b>.</p>

			<p>« Al Adama Mamennouch » , en 1986 , a réalisé un succès sans précédent au Maroc et à l’échelon international ; surtout dans le Maghreb et les pays du Golf .</p>

			<p>Ne pouvant plus suivre le rythme de la demande du marché, le producteur de la chanson, néglige les commandes des distributeurs et laisse la place au piratage pour combler cet engouement.</p>

			<p>Plusieurs autres artistes ont repris ce best-seller : Milouda, Raymond, Rachid LAMRINI, LAASRI, SEIF, et bien d'autres ...</p>

			<p>Fatima BENAGUIDA, commence ainsi une tournée de concerts internationale, et s'arrête en Belgique pour s'y installer.</p>

			<p>En parallèle avec l'art, elle refait ses études et se lance dans le social, qui lui permet d'exprimer sur le terrain sa générosité, son amour et son assistance ;  A ce jour elle exerce toujours son boulot d'aide-soignante dans un hôpital psychiatrique pour les personnes âgées.</p>

			<p>Elle décide également de fonder une famille et vivre amplement son rôle d'épouse et de maman de 3 enfants (2 garçons et une fille).</p>

			<p>20 ans d'absence, à contre coeur , et après l'approbation de la famille et la persistance des amis artistes et des proches , Fatima alias Fatine BENAGUIDA revient en Force et revoit son tube , le ré-enregistre avec de nouvelles paroles  et une nouvelle réorchestration ; une collaboration fructueuse avec Taoufik ABOU ZOUHEIR et Morad EL GZANAY .</p>

			<p>AL ADAMA MAMENNOUCH est un retour logique du joyau au bercail.</p>

			<p>Un tout pour lui permettre de tracer sa vraie carrière dans la chanson marocaine moderne ;  ainsi rêvée dès son jeune âge.</p>

			<p>ANSI AL ADAMA MAMENNOUCH lancée en mars 2015 , l’artiste retrouve goût à la production et enregistre une série de nouvelles chansons . La plus récente est SAD AL BAB , une chanson de 3’50 , écrite et composée par Imad AL MAGHRIBI et arrangée par Badr EL MAKHLOUKI.</p>	

			<p>Aussi , la prochaine étape est sous forme d’un cri exceptionnel qui rend hommage à sa ville natale … A suivre !!!</p>
			<?php } ?>


		</div>
		<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
			<div class="Rsocial col-lg-12">
				<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
				<ul class="exemple ex1 righttoleft">
					<h3 class="col-lg-5 col-xs-4 suivez-nous"> تابعنا على :</h3>
					<a id="fb" href=""><li class="col-lg-1"><img src="images/facebook.png" /></li></a>
					<a id="twitter" href=""><li class="col-lg-1"><img src="images/twitter.png" /></li></a>
					<a id="youtube" href=""><li class="col-lg-1"><img src="images/youtube.png" /></li></a>
					<a id="gplus" href=""><li class="col-lg-1"><img src="images/instagram.png" /></li></a>
				</ul>
				<?php } else { ?>
				<ul class="exemple ex1">
					<h3 class="col-lg-5 col-xs-4">SUIVEZ NOUS:</h3>
					<a id="fb" href=""><li class="col-lg-1"><img src="images/facebook.png" /></li></a>
					<a id="twitter" href=""><li class="col-lg-1"><img src="images/twitter.png" /></li></a>
					<a id="youtube" href=""><li class="col-lg-1"><img src="images/youtube.png" /></li></a>
					<a id="gplus" href=""><li class="col-lg-1"><img src="images/instagram.png" /></li></a>
				</ul>
				<?php } ?>
			</div>
		</div>
	</div>
</section>


<?php if (isset($_GET["lang"]) && $_GET["lang"] == "AR-ar" ) { ?>
<style type="text/css">
@font-face {
	src: url('fonts/ae_Hani.ttf') format('ttf');
	font-family: 'ae_Hani' ;
}

h3, .about p {
	font-family: 'ae_Hani' ;
}

.ticket-rub {
    text-align: left;
    float: left;
    margin-left: -30px;
}

.title-rub {
    text-align: right;
    margin-right: -30px;
    float: right;
}

.suivez-nous { float: right;}

</style>
<?php } ?>